name: mcSociety
main: bazu.mcSociety
version: 1.0
author: bazu
api-version: 1.17
depend: [Shopkeepers]

commands:
  게임:
    permission: op
  leaderRight:
    permission: op
  국가정보:

  vote:

  finishMeeting:

  혁명:

  n:

  callAttack:
    permission: op